package com.example.recyclerview.ui.common

object ConstantesUI {
    const val INFORMACION_LOGIN = "Usuarios: \noscar Contraseña: oscar\nJorge Contraseña: jorge\nDoctores: \nDr. Nefario Email: nefario@gmail.com\nDr. Juan Email: juan@gmail.com"
    const val INFORMACION = "Información"
    const val CITA_CONFIRMADA = "Cita confirmada"
    const val CITA_PEDIDA = "Cita pedida"
    const val SESION_CERRADA = "Sesión cerrada"
    const val ERROR_CANCELAR_CITA = "Error al cancelar la cita"
    const val ERROR_CARGAR_PERSONAS = "Error al cargar las personas"
    const val NADA = ""
    const val NOMBRE = "nombre"
    const val ID_DE_LA_CITA = "ID de la cita = "
    const val FECHA_DE_LA_CITA = "Fecha de la cita = "
    const val HORA_DE_LA_CITA = "Hora de la cita = "
    const val LINK_GITHUB = "https://github.com/javierdelacuadra"
    const val ACERCA_DE = "Acerca de"
    const val MENSAJE_ACERCA_DE = "Versión 1.0.0\n" +
            "Desarrollado por Javier de la Cuadra"
    const val ACEPTAR = "Aceptar"
    const val SHOWAPPBAR = "ShowAppBar"
    const val INICIO = "Inicio"
    const val REVISAR_CITAS = "Revisar citas"
    const val LOGIN_CORRECTO_COMO_DOCTOR = "Login correcto como doctor"
    const val LOGIN_INCORRECTO_COMO_DOCTOR = "Login incorrecto como doctor"
    const val LOGIN_CORRECTO_COMO_USUARIO = "Login correcto como usuario"
    const val LOGIN_INCORRECTO_COMO_USUARIO = "Login incorrecto como usuario"
    const val INICIO_DE_SESION_CORRECTO = "Inicio de sesión correcto"
    const val EL_NOMBRE_O_EL_EMAIL_SON_INCORRECTOS = "El nombre o el email son incorrectos"
    const val EL_NOMBRE_O_LA_CONTRASENA_SON_INCORRECTOS = "El nombre o la contraseña son incorrectos"
    const val ACCESO_USUARIO = "Acceso Usuario"
    const val ACCESO_DOCTOR = "Acceso Doctor"
    const val SPLASH_LOGO_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/SaludMadrid.svg/1200px-SaludMadrid.svg.png"
    const val USUARIO = "usuario"
    const val DOCTOR = "doctor"
    const val ROL_NADA = "Nada"
    const val DR_JUAN_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Ministru_prezidents_Valdis_Dombrovskis_ofici%C4%81l%C4%81s_pusdien%C4%81s_tiekas_ar_Sp%C4%81nijas_karali_Huanu_Karlosu_I_un_karalieni_Sofiju_%283506936051%29_%28cropped%29.jpg/375px-Ministru_prezidents_Valdis_Dombrovskis_ofici%C4%81l%C4%81s_pusdien%C4%81s_tiekas_ar_Sp%C4%81nijas_karali_Huanu_Karlosu_I_un_karalieni_Sofiju_%283506936051%29_%28cropped%29.jpg"
    const val DRA_ISABEL_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/%28Isabel_D%C3%ADaz_Ayuso%29_Reuni%C3%B3n_del_Grupo_Parlamentario_Popular_en_la_Asamblea_de_Madrid.jpg/330px-%28Isabel_D%C3%ADaz_Ayuso%29_Reuni%C3%B3n_del_Grupo_Parlamentario_Popular_en_la_Asamblea_de_Madrid.jpg"
    const val DR_NEFARIO_URL = "https://static.wikia.nocookie.net/doblaje/images/8/8a/Dr_Nefario.jpg/revision/latest?cb=20181105222548&path-prefix=es"
    const val CITA_PEDIDA_CON_EXITO = "Cita pedida con éxito"
    const val DESHACER = "Deshacer"
    const val EMAIL_USUARIO_PLACEHOLDER = "Email del usuario"
    const val TAG = "TAG"
    const val PEDIR_CITA = "Pedir Cita"
    const val VER_CITAS = "Ver Citas"
}